define([
	'amber/helpers', // pre-fetch, dep of amber/deploy
	'amber/deploy', // pre-fetch, dep of amber/lang
	'amber/lang',
	'amber/codemirror',
    'jquery-ui',
    'amber_lib/jquery-tabby/jquery.textarea',
    'amber_core/IDE',
    'amber_core/Examples',
    'amber_core/Benchfib',
    'bootstrap2.3.2/js/bootstrap',
    'amber_lib/showdown/compressed/showdown',
    './Helios-Core',
    './Helios-Exceptions',
    './Helios-Helpers',
    './Helios-Commands-Core',
    './Helios-Commands-Tools',
    './Helios-Commands-Browser',
    './Helios-Commands-SUnit',
    './Helios-Layout',
    './Helios-KeyBindings',
    './Helios-Browser',
    './Helios-Workspace',
    './Helios-Transcript',
    './Helios-SUnit',
    './Helios-SUnit-Tests',
    './Helios-Debugger',
    './Helios-Inspector',
    './Helios-References',
    './Helios-Announcements',
    './Helios-Workspace-Tests',
    'css!./resources/helios',
	'css!./resources/helios-niflheim',
    'css!./resources/niflheim'
], function (smalltalk) { return smalltalk; });
